project:
  type: website
  output-dir: docs

website:
  title: "STA 9750 Submission Material"
  description: "Course Projects for STA 9750 at Baruch College"
  site-url: "https://emreozb.github.io/STA9750-2025-FALL"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: mp01.qmd
        text: Mini-Project 01
      - href: mp02.qmd
        text: Mini-Project 02
      - href: mp03.qmd
        text: Mini-Project 03
      - href: mp04.qmd
        text: Mini-Project 04
      - href: summary_report.qmd
        text: Final Project - Group Summary
      - href: individual_report.qmd
        text: Final Project - Individual Report       
    search: false

format:
  html:
    theme: darkly
    toc: false
    page-layout: full
    self-contained: false
    embed-resources: false

editor: source
